name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.25']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Build binary
        run: make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gac-${{ matrix.os }}-${{ matrix.go-version }}
          path: build/gac*
